bin: extra features for running citgm in parallel
TheAlphaNerd/citgm pull request #4
Opened 2016-12-03 13:15 UTC by GeorgeAdams95

adds the ability to pass in `-J` or `-j <cores>`.
also updates logging to include module name

2016-12-05 20:28 UTC, MylesBorins requested changes
A whole bunch of nits

2016-12-05 20:28 UTC, TheAlphaNerd commented on README.md
> +  -f, --fail-flaky            Ignore flaky flags. Do not ignore any failures.
please send this as a different PR if you would like. It will need to be updated in the yargs options as well

2016-12-05 20:28 UTC, TheAlphaNerd commented on bin/citgm-all.js
> +  app.parallel = require('os').cpus().length;
please require `os` at the top of the file

2016-12-05 20:28 UTC, TheAlphaNerd commented on bin/citgm-all.js
> +    process.setMaxListeners(process.getMaxListeners() - app.parallel || process.getMaxListeners());
Can we set this once above when the job is set to be parallel

2016-12-05 20:28 UTC, TheAlphaNerd commented on bin/citgm-all.js
> +    process.setMaxListeners(process.getMaxListeners() - app.parallel || process.getMaxListeners());
this could also cause weirdness with the number being lowered when one job finishes

2016-12-05 20:28 UTC, TheAlphaNerd commented on bin/citgm-all.js
> +      log.error(result.name, 'done - the test suite for ' + result.name + ' version ' + result.version + ' failed');
I'd prefer if the title was `result.name + ' done'`

2016-12-05 20:28 UTC, TheAlphaNerd commented on bin/citgm-all.js
> +      log.info(result.name, 'done - the test suite for ' + result.name + ' version ' + result.version + ' passed.');
same as above

2016-12-05 20:28 UTC, TheAlphaNerd commented on bin/citgm-all.js
> +      process.setMaxListeners(process.getMaxListeners() - app.parallel || process.getMaxListeners());
this should only be set once

2016-12-05 20:28 UTC, TheAlphaNerd commented on bin/citgm-all.js
> +    process.setMaxListeners(process.getMaxListeners() - app.parallel || process.getMaxListeners());
this should only be set once

2016-12-05 20:28 UTC, TheAlphaNerd commented on bin/citgm-all.js
> +  process.setMaxListeners(process.getMaxListeners() + app.parallel || process.getMaxListeners());
this should only be set once

2016-12-05 20:28 UTC, TheAlphaNerd commented on lib/grab-project.js
> +  context.emit('data', 'info',context.module.name,'Downloading project: ' + packageName);
please include proper spaces between arguments

also please keep the info regarding npm

`context.module.name + ' npm:'`

2016-12-05 20:28 UTC, TheAlphaNerd commented on lib/grab-project.js
> +    context.emit('data', 'error', context.module.name, 'Download Timed Out');
same as above

2016-12-05 20:28 UTC, TheAlphaNerd commented on lib/grab-project.js
> +    context.emit('data', 'info',context.module.name,'Project downloaded ' + filename);
same as above

2016-12-05 20:28 UTC, TheAlphaNerd commented on lib/npm/install.js
> +  context.emit('data', 'info', context.module.name, 'npm install started');
please keep info re: npm
`context.module.name + ' npm:'`

2016-12-05 20:28 UTC, TheAlphaNerd commented on lib/npm/install.js
> +    context.emit('data', 'error', context.module.name, 'npm-install Timed Out');
same as above

2016-12-05 20:28 UTC, TheAlphaNerd commented on lib/npm/install.js
> +    context.emit('data', 'info', context.module.name, 'npm install successfully completed');
same as above

2016-12-05 20:28 UTC, TheAlphaNerd commented on lib/npm/test.js
> +  context.emit('data', 'info', context.module.name, 'test suite started');
same as above

2016-12-05 20:46 UTC, GeorgeAdams95 commented on bin/citgm-all.js
> +  app.parallel = require('os').cpus().length;
I think that it already is? https://github.com/GeorgeAdams95/citgm/blob/8526bb86dffb7c90bfd8d633b3c5d5e6e1fd884b/bin/citgm-all.js#L4

2016-12-05 20:48 UTC, TheAlphaNerd commented
rad, then no need to require again 😁

On Mon, Dec 5, 2016, 3:46 PM George Adams <notifications@github.com> wrote:

> *@GeorgeAdams95* commented on this pull request.
> ------------------------------
>
> In bin/citgm-all.js <https://github.com/TheAlphaNerd/citgm/pull/4>:
>
> > @@ -54,6 +54,11 @@ if (!lookup) {
>    process.exit(1);
>  }
>
> +if (app.autoParallel) {
> +  app.parallel = require('os').cpus().length;
>
> I think that it already is?
> https://github.com/GeorgeAdams95/citgm/blob/8526bb86dffb7c90bfd8d633b3c5d5e6e1fd884b/bin/citgm-all.js#L4
>
> —
> You are receiving this because you commented.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/TheAlphaNerd/citgm/pull/4>, or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAecV30uzhSWVUZG6eMEqPpjqdy59IYXks5rFHgYgaJpZM4LDSml>
> .
>

2016-12-06 00:44 UTC, MylesBorins requested changes
Some small nits.

Do you think we should include the module version along with the name in the logging?

2016-12-06 00:44 UTC, TheAlphaNerd commented on bin/citgm-all.js
> +process.setMaxListeners(process.getMaxListeners() + app.parallel || process.getMaxListeners());
I think this needs to happen down at line 59 or `app.parallel` will not exist yet

2016-12-06 00:44 UTC, TheAlphaNerd commented on lib/citgm.js
> +
I don't think you meant to add this white space here

2016-12-06 01:51 UTC, TheAlphaNerd commented
@GeorgeAdams95 there are also quite a few more instaneces of `context.emit` in the code base. can you please update them all

2016-12-06 10:06 UTC, GeorgeAdams95 commented
@TheAlphaNerd So i have fixed those nits and I think that I have covered all the context.emits

2016-12-06 21:06 UTC, MylesBorins requested changes
a few more small nits

2016-12-06 21:06 UTC, TheAlphaNerd commented on bin/citgm-all.js
> +process.setMaxListeners(process.getMaxListeners() + app.parallel || process.getMaxListeners());
should this value not be `app.parallel`?

2016-12-06 21:06 UTC, TheAlphaNerd commented on lib/lookup.js
> +        context.emit('info', 'lookup-script', rep.script);
this should have the module name included

2016-12-06 21:06 UTC, TheAlphaNerd commented on lib/lookup.js
> +        context.emit('info', 'lookup-replace', url);
this should have the module name included

2016-12-07 09:52 UTC, GeorgeAdams95 commented on bin/citgm-all.js
> +process.setMaxListeners(process.getMaxListeners() + app.parallel || process.getMaxListeners());
yeah you can do it that way I suppose

2016-12-07 09:55 UTC, GeorgeAdams95 commented
updated PTAL

2016-12-08 15:44 UTC, MylesBorins approved these changes
LGTM

2016-12-08 15:45 UTC, TheAlphaNerd commented
landed in 06edae10b2

2016-12-08 15:45 UTC, closed without merging